[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "ens-contracts/=lib/ens-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
